import Head from 'next/head'
import styles from '../styles/Home.module.css'
import convertibleMarkContract from "../util/contractDao/ConvertibleMarkContract";
import {useEffect, useState} from "react";
import providerDao from "../util/providerDao";
import {utils} from "ethers";

export default function Home() {
    const [balance, setBalance] = useState(0);
    const [address, setAddress] = useState(undefined);
    const [addresses, setAddresses] = useState([]);
    const [receiverAddress, setReceiverAddress] = useState("");
    const [receiverAmount, setReceiverAmount] = useState(10);

    const provider = providerDao?.getMetamaskProvider();
    const signer = provider?.getSigner()

    useEffect(() => {
        async function asyncFunction() {
            const accounts = await provider?.listAccounts();
            setAddresses(accounts)

            if (!!accounts && accounts.length > 0) {
                setAddress(accounts[0])
                try {
                    const blnc = await convertibleMarkContract.balanceOf(address).call();
                    setBalance(blnc)
                } catch (e) {
                    console.log("Can't get a balance.", e)
                }
            }


        }

        asyncFunction()
    }, [address])

    async function onSubmit(event) {
        event.preventDefault();

        if (receiverAmount > balance) {
            window.alert("Receiver amount is less than current balance!")
            return false;
        }
        if (!!address) {
            const contract = convertibleMarkContract.connect(signer);
            await contract.transfer(receiverAddress, utils.formatEther(receiverAmount));
        }
        return false;
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <select>
                {
                    addresses?.map((value, index) => (
                        <option key={index}>{value}</option>
                    ))
                }
            </select>
            <p>{balance} KM ({address})</p>

            <form onSubmit={async event => await onSubmit(event)}>
                <p>Send crypto KM to wallet:</p>
                <input type={"text"} value={receiverAddress} onChange={e => setReceiverAddress(e.target.value)}/>
                <input type={"number"} value={receiverAmount}
                       onChange={e => setReceiverAmount(parseFloat(e.target.value))}/>
                <input type={"submit"} value={"Send money"}/>
            </form>

        </div>
    )
}
